[package]
name = "journeymap_viewer"
version = "0.1.0"
edition = "2024"

[profile.dev.package.'*']
opt-level = 3

[dependencies]
egui-macroquad = "0.17.3"
macroquad = "0.4.14"
regex = "1.11.2"
rfd = "0.15.4"
